### ISSUE TITLE
Prerelease 1 To-Do List

### ISSUE THREAD

**Issue by Veilza** [WoD5E-Developers/wod5e#47]
Prerelease 1 is _mostly_ ready to go, but there are a few minor things before it can be pushed into a release.

- [x] Finish up custom disciplines, gifts, and edges
- [x] SPC and group sheets need a little more cleanup
- [x] New biography tab
- [x] Some colours on the vampire/werewolf/hunter themes and dark theme need a once-over in case adjustments are needed
- [x] Double check to ensure all old fields and buttons made the transition over to the new sheets - Frenzy for Vampires and Werewolves still need a place.
- [x] Limited sheets need to be checked to ensure their styling is right, and a setting to hide splat-specific styling on the Limited view
- [ ] Create settings to enable the changing of core splat colours

Everything else that will be in the 5.0 update will be gotten to after Prerelease 1 is out. So far the main things this prerelease is responsible for are:

- #5 
- #22 
- #42 
- #12 
- #13
