### ISSUE TITLE
Prerelease 2 Checklist & Feedback Resolution

### ISSUE THREAD

**Issue by Veilza** [WoD5E-Developers/wod5e#57]
Prerelease 2 Checklist:

- [x] - Better tracking and automation of the Experience page
- [x] - Custom Edges/Gifts
- [x] - Alphabetical sorting of skills/attributes/etc based on language
- [x] - Localization of Werewolf form abilities
- [x] - Make XP page actually track total / expended XP automatically, add edit and delete buttons for experiences

Feedback Resolution
- [x] - #54 
- [x] - #55 
- [x] - #56 
- [x] - Resolve issue with the ProseMirror buttons not all being able to be seen on smaller widths
- [x] - Fix SVG files being too small when used as icons
- [x] - Allow the SPC type selector to move somewhere else if the actor banner is disabled
- [x] - Hide XP Tab on SPC sheets
- [x] - Fix issue where too many custom disciplines will cause opening an actor sheet to take forever
- [x] - Fix some issues where styling wasn't covered; willpower rerolls are one
