### ISSUE TITLE
5.0.0 Checklist

### ISSUE THREAD

**Issue by Veilza** [WoD5E-Developers/wod5e#76]
5.0 Milestone To-Do List
- [x] Add a menu for changing splat colours
- [x] Expendable features/equipment
- [x] Create impairment conditions
- [x] Add Werewolf token changes on form change
- [x] Add "Update from data ID" (items on actor sheets) and "Update all items by data ID" (items in world/compendiums) buttons on items

Feature Requests
- [x] Print a chat card when choosing to Ride the Wave (Vampire sheet, Frenzy)
- [x] Add the ability to suppress a condition's effects
- [x] Allow the background of sheets to be changed

Bugs & Feedback
- [x] Allow Conditions to be removed without unlocking the sheet
- [x] Delete button on custom modifiers isn't working
- [x] If a negative modifier is greater than the pool, the roll won't happen; dicepools should be a minimum of 1
- [x] Power items within compendiums never get migrated
- [x] Text and checkboxes not updating on sheets
- [x] Text editor on itemsheets not taking up full height of the page
- [x] Allow for Resonance items to be removed
